"""Regenerate the `submit/` folder from the canonical docs.

The submission form takes a file per slot, so those files used to be maintained
by hand alongside `docs/`. That is how numbers go stale: the case study said one
thing and the evaluation results said another. Now `submit/` is generated, and
`--check` fails if it has drifted, so CI or a pre-commit run catches it.

Run:  python scripts/build_submission.py
      python scripts/build_submission.py --check
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
SUBMIT = ROOT / "submit"
RESULTS = ROOT / "evaluation" / "results" / "LATEST.md"

BANNER = (
    "<!-- Generated by scripts/build_submission.py. Edit the source under docs/ "
    "and re-run, do not edit this file. -->\n\n"
)

# target filename -> source documents, concatenated in order
BUNDLES: dict[str, list[Path]] = {
    "CASE_STUDY.md": [DOCS / "CASE_STUDY.md"],
    "AI_COLLABORATION.md": [DOCS / "AI_COLLABORATION.md"],
    "EVALUATION_PACKAGE.md": [DOCS / "EVALUATION.md", RESULTS],
    "ARCHITECTURE.md": [DOCS / "ARCHITECTURE.md"],
    "RUNBOOK.md": [DOCS / "RUNBOOK.md"],
}

SEPARATOR = "\n\n---\n\n"


def _relative(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def render(target: str) -> str:
    sources = BUNDLES[target]
    missing = [s for s in sources if not s.exists()]
    if missing:
        raise FileNotFoundError(
            f"{target} needs {', '.join(_relative(m) for m in missing)}. "
            "Run `python -m packet_review_os eval` first if the results file is missing."
        )
    provenance = "Sources: " + ", ".join(f"`{_relative(s)}`" for s in sources) + "\n\n"
    body = SEPARATOR.join(s.read_text(encoding="utf-8").strip() for s in sources)
    return BANNER + provenance + body + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Regenerate submit/ from docs/.")
    parser.add_argument("--check", action="store_true", help="Fail if submit/ is out of date.")
    args = parser.parse_args(argv)

    SUBMIT.mkdir(exist_ok=True)
    stale: list[str] = []
    for target in BUNDLES:
        rendered = render(target)
        path = SUBMIT / target
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current == rendered:
            print(f"  unchanged  submit/{target}")
            continue
        if args.check:
            stale.append(target)
            continue
        path.write_text(rendered, encoding="utf-8")
        print(f"  written    submit/{target}")

    if stale:
        print(
            "\nsubmit/ is out of date: " + ", ".join(stale) + "\nRun: python scripts/build_submission.py",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
